import 'dart:io';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../core/services/mock_firebase_service.dart';
import '../../core/theme/app_colors.dart';
import '../../core/utils/translation.dart';
import '../state_management/auth_notifier.dart';
import '../state_management/shared_state.dart';
import '../widgets/glass_card.dart';

/// Màn hình Cá nhân (Profile Screen) tích hợp demo các dịch vụ Firebase
class ProfilePage extends StatefulWidget {
  const ProfilePage({super.key});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  bool _isExporting = false;
  String? _exportedUrl;

  Future<void> _exportPdfReport(BuildContext context) async {
    setState(() {
      _isExporting = true;
      _exportedUrl = null;
    });

    try {
      final topic = SharedState.activeQueryNotifier.value.isNotEmpty
          ? SharedState.activeQueryNotifier.value
          : 'Artificial Intelligence';
      final publications = SharedState.filteredPublicationsNotifier.value;

      // 1. Tạo tài liệu PDF thực tế bằng thư viện pdf
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Padding(
              padding: const pw.EdgeInsets.all(32),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'JOURNAL TREND ANALYZER - ACADEMIC REPORT',
                    style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Divider(),
                  pw.SizedBox(height: 15),
                  pw.Text('Research Topic: $topic', style: pw.TextStyle(fontSize: 14)),
                  pw.Text('Total Matching Publications: ${publications.length}', style: pw.TextStyle(fontSize: 14)),
                  pw.Text('Date Generated: ${DateTime.now().toLocal()}', style: pw.TextStyle(fontSize: 12)),
                  pw.SizedBox(height: 30),
                  pw.Text('Report Summary:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 10),
                  pw.Text(
                    'This report details research trends compiled from the OpenAlex academic API '
                    'for the topic "$topic". The dataset contains ${publications.length} publications. '
                    'Additional statistical details including citation distributions, keyword frequencies, '
                    'and publishing source analyses have been saved securely.',
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                  pw.SizedBox(height: 50),
                  pw.Align(
                    alignment: pw.Alignment.centerRight,
                    child: pw.Text('Generated by Firebase Storage PDF Exporter', style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic)),
                  ),
                ],
              ),
            );
          },
        ),
      );

      // 2. Ghi tệp tạm thời vào bộ nhớ thiết bị
      final outputDir = await getTemporaryDirectory();
      final pdfPath = '${outputDir.path}/report_${topic.replaceAll(' ', '_')}.pdf';
      final file = File(pdfPath);
      await file.writeAsBytes(await pdf.save());

      // 3. Tải tệp lên Mock Firebase Storage
      final downloadUrl = await MockFirebaseService.instance.uploadPdfReport(
        topic,
        await file.readAsBytes(),
      );

      setState(() {
        _exportedUrl = downloadUrl;
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Báo cáo PDF đã được xuất và tải lên Firebase Storage thành công!'),
            backgroundColor: AppColors.success,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Lỗi xuất báo cáo: $e'),
            backgroundColor: AppColors.error,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } finally {
      setState(() {
        _isExporting = false;
      });
    }
  }

  void _simulatePushNotification() {
    final List<Map<String, String>> templates = [
      {
        'title': 'New trending research topic: Deep Learning',
        'body': 'Recent publications on Deep Learning show a significant increase of 35% in citation rates.'
      },
      {
        'title': 'Highly cited publication alert',
        'body': 'A paper on Quantum Computing has crossed 1,200 citations this month.'
      },
      {
        'title': 'Research trend updates: Renewable Energy',
        'body': 'Renewable Energy journals have added 150 new publications this week.'
      }
    ];

    // Chọn ngẫu nhiên một mẫu thông báo
    final template = (templates..shuffle()).first;
    MockFirebaseService.instance.simulateIncomingNotification(
      template['title']!,
      template['body']!,
    );

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Đã nhận thông báo đẩy: ${template['title']}'),
        backgroundColor: AppColors.info,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  Future<void> _openDownloadUrl(String url) async {
    final uri = Uri.parse(url);
    try {
      // Vì là mock URL nên ta dùng link mock mở trình duyệt ngoài
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } catch (_) {
      // Fallback nếu không mở được link mock
      if (mounted) {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text('Tải báo cáo PDF'),
            content: SelectableText('Đường dẫn tải báo cáo:\n\n$url'),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: const Text('Đóng'),
              ),
            ],
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final auth = Provider.of<AuthNotifier>(context);
    final user = auth.currentUser;

    return Scaffold(
      appBar: AppBar(
        title: Text(
          'profile_tab'.tr(),
          style: GoogleFonts.outfit(fontWeight: FontWeight.bold),
        ),
      ),
      body: Container(
        height: double.infinity,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: isDark
                ? [const Color(0xFF102828), const Color(0xFF0C1D1D)]
                : [const Color(0xFF235C5C), const Color(0xFF1A4747)],
          ),
        ),
        child: ListenableBuilder(
          listenable: MockFirebaseService.instance,
          builder: (context, _) {
            final fService = MockFirebaseService.instance;

            return SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // 1. Thông tin người dùng (User Card)
                  _buildUserCard(user, auth, theme),
                  const SizedBox(height: 20),

                  // 2. Cấu hình từ xa (Remote Config Panel)
                  _buildRemoteConfigCard(fService, theme),
                  const SizedBox(height: 20),

                  // 3. Xuất báo cáo và Storage (Report Export Card)
                  _buildExportReportCard(fService, theme),
                  const SizedBox(height: 20),

                  // 4. Theo dõi lỗi (Crashlytics Card)
                  _buildCrashlyticsCard(fService, theme),
                  const SizedBox(height: 20),

                  // 5. Trung tâm thông báo (Notification Center Card)
                  _buildNotificationCenterCard(fService, theme),
                  const SizedBox(height: 20),

                  // 6. Nhật ký sự kiện Analytics (Debug Event Log)
                  _buildAnalyticsLogsCard(fService, theme),
                  const SizedBox(height: 24),
                ],
              ),
            );
          },
        ),
      ),
    );
  }

  Widget _buildUserCard(MockFirebaseUser? user, AuthNotifier auth, ThemeData theme) {
    return GlassCard(
      borderColor: const Color(0xFF80CBC4).withOpacity(0.3),
      child: Row(
        children: [
          CircleAvatar(
            radius: 30,
            backgroundImage: NetworkImage(
              user?.photoUrl ??
                  'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&h=150&q=80',
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  user?.displayName ?? 'Nguyen Van A',
                  style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16),
                ),
                Text(
                  user?.email ?? 'nguyenvana.prm393@gmail.com',
                  style: const TextStyle(color: Colors.white60, fontSize: 12),
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
          IconButton(
            icon: const Icon(Icons.logout_rounded, color: Colors.redAccent),
            tooltip: 'Đăng xuất',
            onPressed: () {
              auth.signOut();
            },
          ),
        ],
      ),
    );
  }

  Widget _buildRemoteConfigCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.settings_suggest_rounded, color: Color(0xFF80CBC4)),
              const SizedBox(width: 8),
              Text(
                'Firebase Remote Config Demo',
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
              ),
            ],
          ),
          const SizedBox(height: 8),
          const Text(
            'Giả lập thay đổi cấu hình hiển thị danh sách từ xa của Firebase Console.',
            style: TextStyle(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 16),
          // Điều chỉnh giới hạn tạp chí tối đa
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Tạp chí tối đa hiển thị: ${service.maxJournalsDisplayed}',
                      style: const TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold),
                    ),
                    Slider(
                      value: service.maxJournalsDisplayed.toDouble(),
                      min: 1,
                      max: 20,
                      divisions: 19,
                      activeColor: const Color(0xFF80CBC4),
                      inactiveColor: Colors.white12,
                      onChanged: (val) {
                        service.updateRemoteConfig(
                          maxJournals: val.toInt(),
                          maxKeywords: service.maxKeywordsDisplayed,
                        );
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
          // Điều chỉnh giới hạn từ khóa tối đa
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Từ khóa tối đa hiển thị: ${service.maxKeywordsDisplayed}',
                      style: const TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold),
                    ),
                    Slider(
                      value: service.maxKeywordsDisplayed.toDouble(),
                      min: 2,
                      max: 30,
                      divisions: 28,
                      activeColor: const Color(0xFF80CBC4),
                      inactiveColor: Colors.white12,
                      onChanged: (val) {
                        service.updateRemoteConfig(
                          maxJournals: service.maxJournalsDisplayed,
                          maxKeywords: val.toInt(),
                        );
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildExportReportCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.cloud_upload_rounded, color: Color(0xFF80CBC4)),
              const SizedBox(width: 8),
              Text(
                'Firebase Storage Report Exporter',
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
              ),
            ],
          ),
          const SizedBox(height: 8),
          const Text(
            'Tải dữ liệu phân tích đề tài hiện tại về máy dạng PDF và lưu trữ trên Firebase Cloud Storage.',
            style: TextStyle(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 16),
          if (_isExporting)
            const Center(
              child: Column(
                children: [
                  CircularProgressIndicator(color: Color(0xFF80CBC4)),
                  SizedBox(height: 8),
                  Text('Đang tạo báo cáo & tải lên Firebase Storage...', style: TextStyle(color: Colors.white70, fontSize: 12)),
                ],
              ),
            )
          else ...[
            ElevatedButton.icon(
              onPressed: () => _exportPdfReport(context),
              icon: const Icon(Icons.picture_as_pdf_rounded),
              label: const Text('Xuất báo cáo PDF'),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF80CBC4),
                foregroundColor: AppColors.primaryText,
                padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            if (_exportedUrl != null) ...[
              const SizedBox(height: 16),
              const Text(
                'Đường dẫn tệp báo cáo đã tải lên:',
                style: TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 6),
              GestureDetector(
                onTap: () => _openDownloadUrl(_exportedUrl!),
                child: Text(
                  _exportedUrl!,
                  style: const TextStyle(
                    color: Colors.cyanAccent,
                    fontSize: 12,
                    decoration: TextDecoration.underline,
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            ],
          ],
        ],
      ),
    );
  }

  Widget _buildCrashlyticsCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.bug_report_rounded, color: Colors.redAccent),
              const SizedBox(width: 8),
              Text(
                'Firebase Crashlytics Demo',
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
              ),
            ],
          ),
          const SizedBox(height: 8),
          const Text(
            'Mô phỏng ghi nhận lỗi ngoại lệ không đồng bộ hoặc kích hoạt sập ứng dụng để kiểm thử báo cáo Crashlytics.',
            style: TextStyle(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: () {
                    try {
                      throw StateError('Simulated Null Pointer Exception');
                    } catch (e, stack) {
                      service.logHandledException(e, stack);
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: const Text('Đã ghi nhận Exception thành công lên Crashlytics!'),
                          backgroundColor: AppColors.success,
                          behavior: SnackBarBehavior.floating,
                        ),
                      );
                    }
                  },
                  style: OutlinedButton.styleFrom(
                    foregroundColor: Colors.white70,
                    side: const BorderSide(color: Colors.white30),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                  child: const Text('Handled Exception', style: TextStyle(fontSize: 12)),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: ElevatedButton(
                  onPressed: () {
                    // Trigger test crash
                    service.triggerTestCrash();
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.redAccent.withOpacity(0.8),
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                  child: const Text('Trigger Test Crash', style: TextStyle(fontSize: 12)),
                ),
              ),
            ],
          ),
          if (service.loggedExceptions.isNotEmpty) ...[
            const SizedBox(height: 12),
            Text(
              'Số ngoại lệ đã bắt đầu ghi nhận: ${service.loggedExceptions.length}',
              style: const TextStyle(color: Colors.white60, fontSize: 11, fontStyle: FontStyle.italic),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildNotificationCenterCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  const Icon(Icons.notifications_active_rounded, color: Color(0xFF80CBC4)),
                  const SizedBox(width: 8),
                  Text(
                    'Notification Center (FCM)',
                    style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
                  ),
                ],
              ),
              IconButton(
                icon: const Icon(Icons.add_alert_rounded, color: Color(0xFF80CBC4), size: 20),
                tooltip: 'Mô phỏng thông báo mới',
                onPressed: _simulatePushNotification,
              ),
            ],
          ),
          const SizedBox(height: 4),
          const Text(
            'Trung tâm hiển thị thông báo đẩy được gửi trực tuyến thông qua Firebase Cloud Messaging.',
            style: TextStyle(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 12),
          if (service.notifications.isEmpty)
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 20.0),
              child: Center(
                child: Text('Không có thông báo nào.', style: TextStyle(color: Colors.white30, fontSize: 13)),
              ),
            )
          else
            ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: service.notifications.length > 3 ? 3 : service.notifications.length,
              itemBuilder: (context, index) {
                final notif = service.notifications[index];
                return Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.04),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.white.withOpacity(0.05)),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Expanded(
                            child: Text(
                              notif.title,
                              style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 12),
                            ),
                          ),
                          Text(
                            '${notif.timestamp.hour}:${notif.timestamp.minute.toString().padLeft(2, '0')}',
                            style: const TextStyle(color: Colors.white30, fontSize: 10),
                          ),
                        ],
                      ),
                      const SizedBox(height: 4),
                      Text(
                        notif.body,
                        style: const TextStyle(color: Colors.white60, fontSize: 11),
                      ),
                    ],
                  ),
                );
              },
            ),
        ],
      ),
    );
  }

  Widget _buildAnalyticsLogsCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      borderColor: const Color(0xFF80CBC4).withOpacity(0.2),
      color: Colors.black.withOpacity(0.12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.analytics_rounded, color: Color(0xFF80CBC4)),
              const SizedBox(width: 8),
              Text(
                'Debug Analytics Logs (Báo cáo Minh Chứng)',
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white, fontSize: 14),
              ),
            ],
          ),
          const SizedBox(height: 6),
          const Text(
            'Đây là bảng hiển thị các sự kiện đã gửi lên Firebase Analytics dùng để chụp ảnh minh chứng cho dự án của bạn.',
            style: TextStyle(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 12),
          Container(
            height: 200,
            decoration: BoxDecoration(
              color: Colors.black.withOpacity(0.2),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.white.withOpacity(0.08)),
            ),
            child: service.loggedEvents.isEmpty
                ? const Center(
                    child: Text('Chưa có sự kiện nào được ghi nhận.', style: TextStyle(color: Colors.white24, fontSize: 12)),
                  )
                : ListView.builder(
                    padding: const EdgeInsets.all(8),
                    itemCount: service.loggedEvents.length,
                    itemBuilder: (context, index) {
                      final event = service.loggedEvents[index];
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 10.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  'Event: ${event.name}',
                                  style: const TextStyle(color: Color(0xFF80CBC4), fontWeight: FontWeight.bold, fontSize: 12),
                                ),
                                Text(
                                  '${event.timestamp.hour}:${event.timestamp.minute.toString().padLeft(2, '0')}:${event.timestamp.second.toString().padLeft(2, '0')}',
                                  style: const TextStyle(color: Colors.white38, fontSize: 10),
                                ),
                              ],
                            ),
                            const SizedBox(height: 2),
                            Text(
                              'Params: ${event.parameters.toString()}',
                              style: const TextStyle(color: Colors.white70, fontSize: 11, fontFamily: 'monospace'),
                            ),
                            const Divider(color: Colors.white10),
                          ],
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
