import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:journal_trend_analysis_mb/services/mock_firebase_service.dart';
import 'package:journal_trend_analysis_mb/theme/app_colors.dart';
import 'package:journal_trend_analysis_mb/utils/translation.dart';
import 'package:journal_trend_analysis_mb/viewmodels/auth_notifier.dart';
import 'package:journal_trend_analysis_mb/viewmodels/shared_state.dart';
import 'package:journal_trend_analysis_mb/widgets/glass_card.dart';
import 'package:journal_trend_analysis_mb/screens/detail_page.dart';
import 'package:journal_trend_analysis_mb/models/publication_model.dart';

/// Màn hình Cá nhân (Profile Screen) tích hợp demo các dịch vụ Firebase
class ProfilePage extends StatefulWidget {
  const ProfilePage({super.key});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  bool _isExporting = false;
  String? _exportedUrl;
  bool _isScanning = false;

  Future<void> _exportPdfReport(BuildContext context) async {
    setState(() {
      _isExporting = true;
      _exportedUrl = null;
    });

    try {
      final topic = SharedState.activeQueryNotifier.value.isNotEmpty
          ? SharedState.activeQueryNotifier.value
          : 'Artificial Intelligence';
      final publications = SharedState.filteredPublicationsNotifier.value;

      // 1. Tạo tài liệu PDF thực tế bằng thư viện pdf
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Padding(
              padding: const pw.EdgeInsets.all(32),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'JOURNAL TREND ANALYZER - ACADEMIC REPORT',
                    style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Divider(),
                  pw.SizedBox(height: 15),
                  pw.Text('Research Topic: $topic', style: pw.TextStyle(fontSize: 14)),
                  pw.Text('Total Matching Publications: ${publications.length}', style: pw.TextStyle(fontSize: 14)),
                  pw.Text('Date Generated: ${DateTime.now().toLocal()}', style: pw.TextStyle(fontSize: 12)),
                  pw.SizedBox(height: 30),
                  pw.Text('Report Summary:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 10),
                  pw.Text(
                    'This report details research trends compiled from the OpenAlex academic API '
                    'for the topic "$topic". The dataset contains ${publications.length} publications. '
                    'Additional statistical details including citation distributions, keyword frequencies, '
                    'and publishing source analyses have been saved securely.',
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                  pw.SizedBox(height: 50),
                  pw.Align(
                    alignment: pw.Alignment.centerRight,
                    child: pw.Text('Generated by Firebase Storage PDF Exporter', style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic)),
                  ),
                ],
              ),
            );
          },
        ),
      );

      // 2. Ghi tệp tạm thời vào bộ nhớ thiết bị
      final outputDir = await getTemporaryDirectory();
      final pdfPath = '${outputDir.path}/report_${topic.replaceAll(' ', '_')}.pdf';
      final file = File(pdfPath);
      await file.writeAsBytes(await pdf.save());

      // 3. Tải tệp lên Firebase Storage (gọi service tích hợp thực tế/mock)
      final downloadUrl = await MockFirebaseService.instance.uploadPdfReport(
        topic,
        await file.readAsBytes(),
      );

      setState(() {
        _exportedUrl = downloadUrl;
      });

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('upload_success'.tr()),
            backgroundColor: AppColors.success,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${'error_loading_data'.tr()}: $e'),
            backgroundColor: AppColors.error,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } finally {
      setState(() {
        _isExporting = false;
      });
    }
  }

  void _simulatePushNotification() {
    final List<Map<String, String>> templates = [
      {
        'title': 'New trending research topic: Deep Learning',
        'body': 'Recent publications on Deep Learning show a significant increase of 35% in citation rates.',
        'url': 'https://doi.org/10.1145/3613904.3642456',
        'publicationTitle': 'Deep Learning: Modern Trends and Architectures',
        'journalName': 'ACM Transactions on Intelligent Systems',
      },
      {
        'title': 'Highly cited publication alert',
        'body': 'A paper on Quantum Computing has crossed 1,200 citations this month.',
        'url': 'https://doi.org/10.1038/s41586-019-1666-5',
        'publicationTitle': 'Quantum Supremacy using a Programmable Superconducting Processor',
        'journalName': 'Nature',
      },
      {
        'title': 'Research trend updates: Renewable Energy',
        'body': 'Renewable Energy journals have added 150 new publications this week.',
        'url': 'https://doi.org/10.1016/j.rser.2023.113245',
        'publicationTitle': 'Advancements in Solar Cell Efficiency and Grid Integration',
        'journalName': 'Renewable and Sustainable Energy Reviews',
      }
    ];

    final template = (templates..shuffle()).first;
    MockFirebaseService.instance.simulateIncomingNotification(
      template['title']!,
      template['body']!,
      url: template['url']!,
      publicationTitle: template['publicationTitle'],
      journalName: template['journalName'],
    );

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('incoming_notification_alert'.tr().replaceAll('{title}', template['title']!)),
        backgroundColor: AppColors.info,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  Future<void> _scanLatestPublication() async {
    setState(() {
      _isScanning = true;
    });

    final Set<String> keywordsToScan = {
      'Engineering',
      'Data Mining',
      'Economics',
      'Computer Security',
      'Deep Learning',
      'Quantum Computing',
      'Renewable Energy',
      'Artificial Intelligence',
      'Machine Learning',
      'Computer Vision',
      'Psychology',
      'Artificial Intelligence in Healthcare and Education',
      'Political science',
      'Natural Language Processing',
      'Mathematics',
      'Law',
      'Data Science',
      'Computer Science',
    };
    if (SharedState.activeQueryNotifier.value.isNotEmpty) {
      keywordsToScan.add(SharedState.activeQueryNotifier.value);
    }

    int successCount = 0;

    try {
      final List<Future<void>> tasks = keywordsToScan.map((keyword) async {
        try {
          final url = Uri.parse(
            'https://api.openalex.org/works?filter=default.search:${Uri.encodeComponent(keyword)}&sort=publication_date:desc&per_page=1&mailto=minhvtbd12345@fpt.edu.vn',
          );
          final response = await http.get(url, headers: {
            'Accept': 'application/json',
            'User-Agent': 'JournalTrendAnalyzerMobile/1.0',
          }).timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final data = jsonDecode(response.body) as Map<String, dynamic>;
            final results = data['results'] as List?;
            if (results != null && results.isNotEmpty) {
              final latestWork = results[0];
              final title = latestWork['title'] ?? 'No Title';
              final journal = latestWork['primary_location']?['source']?['display_name'] ?? 'Unknown Journal';
              final doi = latestWork['doi']?.toString() ?? '';
              final landingPageUrl = latestWork['primary_location']?['landing_page_url']?.toString() ?? '';
              final latestWorkId = latestWork['id']?.toString() ?? '';
              final publicationUrl = doi.isNotEmpty ? doi : (landingPageUrl.isNotEmpty ? landingPageUrl : latestWorkId);

              // Avoid duplicate notifications by checking publication title
              final isExist = MockFirebaseService.instance.notifications.any((n) => n.body.contains(title));
              if (!isExist) {
                MockFirebaseService.instance.simulateIncomingNotification(
                  'New article for topic: "$keyword"',
                  '"$title" has just been published in the journal $journal.',
                  url: publicationUrl,
                  publicationTitle: title,
                  journalName: journal,
                );
                successCount++;
              }
            }
          }
        } catch (e) {
          debugPrint('[FCM] Error scanning keyword $keyword: $e');
        }
      }).toList();

      await Future.wait(tasks);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(successCount > 0 
              ? 'Scan successful! Found and added $successCount new articles.'
              : 'Scan complete. No new articles found.'),
            backgroundColor: AppColors.success,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error scanning publications: $e'),
            backgroundColor: AppColors.error,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isScanning = false;
        });
      }
    }
  }

  Future<void> _openDownloadUrl(String url) async {
    final uri = Uri.parse(url);
    try {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } catch (_) {
      if (mounted) {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text('firebase_storage'.tr()),
            content: SelectableText('URL:\n\n$url'),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: Text('close_button'.tr()),
              ),
            ],
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final auth = Provider.of<AuthNotifier>(context);
    final user = auth.currentUser;

    return Scaffold(
      appBar: AppBar(
        title: Text(
          'profile_tab'.tr(),
          style: GoogleFonts.outfit(fontWeight: FontWeight.bold),
        ),
      ),
      body: Container(
        height: double.infinity,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: isDark
                ? [const Color(0xFF102828), const Color(0xFF0C1D1D)]
                : [const Color(0xFF235C5C), const Color(0xFF1A4747)],
          ),
        ),
        child: ListenableBuilder(
          listenable: SharedState.languageNotifier,
          builder: (context, _) {
            return ListenableBuilder(
              listenable: MockFirebaseService.instance,
              builder: (context, _) {
                final fService = MockFirebaseService.instance;

                return SingleChildScrollView(
                  padding: const EdgeInsets.only(left: 16.0, right: 16.0, top: 16.0, bottom: 80.0), // Chừa khoảng trống bottom bar
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // 1. Thông tin người dùng (User Card)
                      _buildUserCard(user, auth, theme),
                      const SizedBox(height: 20),

                      // 2. Cấu hình từ xa (Remote Config Panel)
                      _buildRemoteConfigCard(fService, theme),
                      const SizedBox(height: 20),

                      // 3. Xuất báo cáo và Storage (Report Export Card)
                      _buildExportReportCard(fService, theme),
                      const SizedBox(height: 20),

                      // 4. Theo dõi lỗi (Crashlytics Card)
                      _buildCrashlyticsCard(fService, theme),
                      const SizedBox(height: 20),

                      // 5. Trung tâm thông báo (Notification Center Card)
                      _buildNotificationCenterCard(fService, theme),
                      const SizedBox(height: 20),

                      // 6. Nhật ký sự kiện Analytics (Debug Event Log)
                      _buildAnalyticsLogsCard(fService, theme),
                    ],
                  ),
                );
              },
            );
          },
        ),
      ),
    );
  }

  Widget _buildUserCard(MockFirebaseUser? user, AuthNotifier auth, ThemeData theme) {
    return GlassCard(
      borderColor: const Color(0xFF80CBC4).withOpacity(0.3),
      child: Row(
        children: [
          CircleAvatar(
            radius: 30,
            backgroundImage: NetworkImage(
              user?.photoUrl ??
                  'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&h=150&q=80',
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  user?.displayName ?? 'Nguyen Van A',
                  style: GoogleFonts.outfit(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16),
                ),
                const SizedBox(height: 4),
                Text(
                  user?.email ?? 'nguyenvana.prm393@gmail.com',
                  style: GoogleFonts.inter(color: Colors.white60, fontSize: 12),
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
          IconButton(
            icon: const Icon(Icons.logout_rounded, color: Colors.redAccent),
            tooltip: 'sign_out'.tr(),
            onPressed: () {
              auth.signOut();
            },
          ),
        ],
      ),
    );
  }

  Widget _buildRemoteConfigCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      borderRadius: 18,
      color: Colors.white.withOpacity(0.06),
      borderColor: const Color(0xFF4CAF50).withOpacity(0.35), // Green accent border
      borderWidth: 1.0,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: const Color(0xFF4CAF50).withOpacity(0.15),
                ),
                child: const Icon(Icons.settings_suggest_rounded, color: Color(0xFF4CAF50), size: 18),
              ),
              const SizedBox(width: 10),
              Text(
                'firebase_remote_config'.tr(),
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white, fontSize: 15),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            'remote_config_desc'.tr(),
            style: GoogleFonts.inter(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 20),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'max_journals_to_display'.tr(),
                    style: GoogleFonts.inter(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.w600),
                  ),
                  Text(
                    '${service.maxJournalsDisplayed}',
                    style: GoogleFonts.outfit(color: const Color(0xFF4CAF50), fontSize: 14, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
              SliderTheme(
                data: SliderTheme.of(context).copyWith(
                  activeTrackColor: const Color(0xFF4CAF50),
                  inactiveTrackColor: Colors.white12,
                  thumbColor: const Color(0xFF4CAF50),
                  overlayColor: const Color(0xFF4CAF50).withOpacity(0.12),
                  trackHeight: 3,
                ),
                child: Slider(
                  value: service.maxJournalsDisplayed.toDouble(),
                  min: 1,
                  max: 20,
                  divisions: 19,
                  onChanged: (val) {
                    service.updateRemoteConfig(
                      maxJournals: val.toInt(),
                      maxKeywords: service.maxKeywordsDisplayed,
                    );
                  },
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'max_keywords_to_display'.tr(),
                    style: GoogleFonts.inter(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.w600),
                  ),
                  Text(
                    '${service.maxKeywordsDisplayed}',
                    style: GoogleFonts.outfit(color: const Color(0xFF4CAF50), fontSize: 14, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
              SliderTheme(
                data: SliderTheme.of(context).copyWith(
                  activeTrackColor: const Color(0xFF4CAF50),
                  inactiveTrackColor: Colors.white12,
                  thumbColor: const Color(0xFF4CAF50),
                  overlayColor: const Color(0xFF4CAF50).withOpacity(0.12),
                  trackHeight: 3,
                ),
                child: Slider(
                  value: service.maxKeywordsDisplayed.toDouble(),
                  min: 2,
                  max: 30,
                  divisions: 28,
                  onChanged: (val) {
                    service.updateRemoteConfig(
                      maxJournals: service.maxJournalsDisplayed,
                      maxKeywords: val.toInt(),
                    );
                  },
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildExportReportCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      borderRadius: 18,
      color: Colors.white.withOpacity(0.06),
      borderColor: const Color(0xFF2196F3).withOpacity(0.35), // Blue accent border
      borderWidth: 1.0,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: const Color(0xFF2196F3).withOpacity(0.15),
                ),
                child: const Icon(Icons.cloud_upload_rounded, color: Color(0xFF2196F3), size: 18),
              ),
              const SizedBox(width: 10),
              Text(
                'firebase_storage'.tr(),
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white, fontSize: 15),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            'storage_desc'.tr(),
            style: GoogleFonts.inter(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 20),
          if (_isExporting)
            Center(
              child: Padding(
                padding: const EdgeInsets.symmetric(vertical: 8.0),
                child: Column(
                  children: [
                    const SizedBox(
                      width: 24,
                      height: 24,
                      child: CircularProgressIndicator(color: Color(0xFF2196F3), strokeWidth: 2.5),
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'exporting_and_uploading'.tr(),
                      style: GoogleFonts.inter(color: Colors.white70, fontSize: 12),
                    ),
                  ],
                ),
              ),
            )
          else ...[
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: () => _exportPdfReport(context),
                icon: const Icon(Icons.picture_as_pdf_rounded, size: 16),
                label: Text('export_pdf_report'.tr()),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF2196F3),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  elevation: 2,
                ),
              ),
            ),
            if (_exportedUrl != null) ...[
              const SizedBox(height: 16),
              Row(
                children: [
                  const Icon(Icons.check_circle_rounded, color: Colors.greenAccent, size: 14),
                  const SizedBox(width: 6),
                  Text(
                    'upload_success'.tr(),
                    style: GoogleFonts.inter(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
              const SizedBox(height: 6),
              InkWell(
                onTap: () => _openDownloadUrl(_exportedUrl!),
                borderRadius: BorderRadius.circular(8),
                child: Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.04),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.white.withOpacity(0.08)),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.open_in_new_rounded, color: Colors.cyanAccent, size: 14),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          _exportedUrl!,
                          style: GoogleFonts.inter(
                            textStyle: const TextStyle(
                              color: Colors.cyanAccent,
                              fontSize: 11,
                              decoration: TextDecoration.underline,
                            ),
                          ),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ],
        ],
      ),
    );
  }

  Widget _buildCrashlyticsCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      borderRadius: 18,
      color: Colors.white.withOpacity(0.06),
      borderColor: const Color(0xFFE53935).withOpacity(0.35), // Red accent border
      borderWidth: 1.0,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: const Color(0xFFE53935).withOpacity(0.15),
                ),
                child: const Icon(Icons.bug_report_rounded, color: Color(0xFFE53935), size: 18),
              ),
              const SizedBox(width: 10),
              Text(
                'Firebase Crashlytics',
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white, fontSize: 15),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            'crashlytics_desc'.tr(),
            style: GoogleFonts.inter(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 20),
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: () {
                    try {
                      throw StateError('Simulated Handled Exception Log');
                    } catch (e, stack) {
                      service.logHandledException(e, stack);
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text('sent_handled_success'.tr()),
                          backgroundColor: AppColors.success,
                          behavior: SnackBarBehavior.floating,
                        ),
                      );
                    }
                  },
                  style: OutlinedButton.styleFrom(
                    foregroundColor: Colors.white70,
                    side: const BorderSide(color: Colors.white30),
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                  child: Text('handled_exception'.tr(), style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w600)),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: ElevatedButton(
                  onPressed: () {
                    service.triggerTestCrash();
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFE53935),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                    elevation: 2,
                  ),
                  child: Text('trigger_test_crash'.tr(), style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.bold)),
                ),
              ),
            ],
          ),
          if (service.loggedExceptions.isNotEmpty) ...[
            const SizedBox(height: 12),
            Row(
              children: [
                const Icon(Icons.check_circle_outline, color: Colors.redAccent, size: 12),
                const SizedBox(width: 6),
                Text(
                  'recorded_exceptions_count'.tr().replaceAll('{count}', service.loggedExceptions.length.toString()),
                  style: GoogleFonts.inter(color: Colors.white54, fontSize: 11, fontStyle: FontStyle.italic),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildNotificationCenterCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      borderRadius: 18,
      color: Colors.white.withOpacity(0.06),
      borderColor: const Color(0xFFFF9800).withOpacity(0.35), // Orange accent border
      borderWidth: 1.0,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: const Color(0xFFFF9800).withOpacity(0.15),
                      ),
                      child: const Icon(Icons.notifications_active_rounded, color: Color(0xFFFF9800), size: 18),
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'notification_center_fcm'.tr(),
                        style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white, fontSize: 14),
                        overflow: TextOverflow.ellipsis,
                        maxLines: 1,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              Row(
                children: [
                  IconButton(
                    icon: _isScanning
                        ? const SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(
                              strokeWidth: 2.0,
                              valueColor: AlwaysStoppedAnimation<Color>(Color(0xFFFF9800)),
                            ),
                          )
                        : const Icon(Icons.sync_rounded, color: Color(0xFFFF9800), size: 20),
                    tooltip: 'Quét bài báo mới nhất',
                    onPressed: _isScanning ? null : _scanLatestPublication,
                  ),
                  IconButton(
                    icon: const Icon(Icons.add_alert_rounded, color: Color(0xFFFF9800), size: 20),
                    tooltip: 'simulate_incoming_notification'.tr(),
                    onPressed: _simulatePushNotification,
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            'fcm_desc'.tr(),
            style: GoogleFonts.inter(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 16),
          if (service.notifications.isEmpty)
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 24.0),
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.02),
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: Colors.white.withOpacity(0.04)),
              ),
              child: Center(
                child: Text('no_notifications'.tr(), style: GoogleFonts.inter(color: Colors.white30, fontSize: 13)),
              ),
            )
          else
            ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: service.notifications.length,
              itemBuilder: (context, index) {
                final notif = service.notifications[index];
                return Card(
                  margin: const EdgeInsets.only(bottom: 10),
                  color: Colors.transparent,
                  elevation: 0,
                  child: InkWell(
                    onTap: () {
                      final publication = Publication(
                        id: notif.id,
                        title: notif.publicationTitle ?? notif.title,
                        publicationYear: notif.timestamp.year,
                        citationCount: 0,
                        doi: notif.url,
                        journalName: notif.journalName ?? 'Unknown Journal',
                        authors: const [],
                        abstractText: notif.body,
                        concepts: const [],
                        topics: const [],
                        landingPageUrl: notif.url,
                      );

                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => DetailPage(publication: publication),
                        ),
                      );
                    },
                    borderRadius: BorderRadius.circular(12),
                    child: Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.04),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: Colors.white.withOpacity(0.06)),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Expanded(
                                child: Text(
                                  notif.title,
                                  style: GoogleFonts.outfit(
                                    textStyle: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 13),
                                  ),
                                ),
                              ),
                              const SizedBox(width: 8),
                              if (notif.url != null && notif.url!.isNotEmpty) ...[
                                InkWell(
                                  onTap: () => _openDownloadUrl(notif.url!),
                                  child: Container(
                                    padding: const EdgeInsets.all(4),
                                    decoration: BoxDecoration(
                                      color: Colors.white.withOpacity(0.1),
                                      shape: BoxShape.circle,
                                    ),
                                    child: const Icon(
                                      Icons.open_in_new_rounded,
                                      color: Color(0xFFFF9800),
                                      size: 14,
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 8),
                              ],
                              Text(
                                '${notif.timestamp.hour.toString().padLeft(2, '0')}:${notif.timestamp.minute.toString().padLeft(2, '0')}',
                                style: GoogleFonts.inter(
                                  textStyle: const TextStyle(color: Colors.white38, fontSize: 10, fontWeight: FontWeight.w600),
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 6),
                          Text(
                            notif.body,
                            style: GoogleFonts.inter(
                              textStyle: const TextStyle(color: Colors.white60, fontSize: 11, height: 1.4),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                );
              },
            ),
        ],
      ),
    );
  }

  Widget _buildAnalyticsLogsCard(MockFirebaseService service, ThemeData theme) {
    return GlassCard(
      borderRadius: 18,
      borderColor: const Color(0xFF00E676).withOpacity(0.25),
      color: Colors.black.withOpacity(0.35),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: const Color(0xFF00E676).withOpacity(0.12),
                ),
                child: const Icon(Icons.analytics_rounded, color: Color(0xFF00E676), size: 18),
              ),
              const SizedBox(width: 10),
              Text(
                'debug_analytics_logs'.tr(),
                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white, fontSize: 14),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            'analytics_desc'.tr(),
            style: GoogleFonts.inter(color: Colors.white60, fontSize: 11),
          ),
          const SizedBox(height: 16),
          Container(
            height: 180,
            decoration: BoxDecoration(
              color: const Color(0xFF0A0F1D),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.white.withOpacity(0.08)),
            ),
            child: service.loggedEvents.isEmpty
                ? Center(
                    child: Text(
                      '// Waiting for events...',
                      style: GoogleFonts.spaceMono(
                        textStyle: const TextStyle(color: Colors.white24, fontSize: 12),
                      ),
                    ),
                  )
                : ListView.builder(
                    padding: const EdgeInsets.all(10),
                    itemCount: service.loggedEvents.length,
                    itemBuilder: (context, index) {
                      final event = service.loggedEvents[index];
                      final timeStr = '${event.timestamp.hour.toString().padLeft(2, '0')}:${event.timestamp.minute.toString().padLeft(2, '0')}:${event.timestamp.second.toString().padLeft(2, '0')}';
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 12.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  '> Event: ${event.name}',
                                  style: GoogleFonts.spaceMono(
                                    textStyle: const TextStyle(color: Color(0xFF00E676), fontWeight: FontWeight.bold, fontSize: 11),
                                  ),
                                ),
                                Text(
                                  timeStr,
                                  style: GoogleFonts.spaceMono(
                                    textStyle: const TextStyle(color: Colors.white30, fontSize: 10),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 4),
                            Text(
                              '  params: ${event.parameters.toString()}',
                              style: GoogleFonts.spaceMono(
                                textStyle: const TextStyle(color: Colors.white70, fontSize: 10),
                              ),
                            ),
                            const SizedBox(height: 8),
                            Container(height: 1, color: Colors.white10),
                          ],
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
